name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Application to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit on error

            # Install required packages
            sudo apt update
            sudo apt install -y nodejs npm nginx git
            sudo npm install -g pm2

            # Clone or pull latest code
            mkdir -p ~/app
            cd ~/app

            if [ ! -d "simple-fullstack-app" ]; then
              git clone https://github.com/Shri9345/simple-fullstack-app.git
            else
              cd simple-fullstack-app
              git fetch origin
              git reset --hard origin/main
              cd ..
            fi

            # Start backend with PM2
            cd ~/app/simple-fullstack-app/backend
            npm install
            pm2 delete backend || true
            pm2 start server.js --name backend

            # Deploy frontend to Nginx
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/app/simple-fullstack-app/frontend/* /var/www/html/
            sudo systemctl reload nginx
          EOF
