name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy backend
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e  # Exit if any command fails
          
          # Basic updates and installations
          sudo apt update
          sudo apt install -y nodejs npm nginx

          # Install pm2 globally if not installed
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          # Clone repo if not present
          mkdir -p ~/app
          cd ~/app
          if [ ! -d "simple-fullstack-app" ]; then
            git clone https://github.com/Shri9345/simple-fullstack-app.git
          fi

          cd simple-fullstack-app
          git pull origin main

          # Backend setup
          cd backend
          npm install

          # Restart backend with pm2
          pm2 delete backend || true
          pm2 start server.js --name backend

          # Save PM2 state and configure startup (optional)
          pm2 save
          pm2 startup systemd -u $USER --hp $HOME
        EOF
