- name: Deploy backend
  run: |
    ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      set -e  # Exit on error

      sudo apt update
      sudo apt install -y nodejs npm nginx

      # Install pm2 if not present
      if ! command -v pm2 &> /dev/null; then
        sudo npm install -g pm2
      fi

      # Setup project
      mkdir -p ~/app
      cd ~/app

      if [ ! -d "simple-fullstack-app" ]; then
        git clone https://github.com/Shri9345/simple-fullstack-app.git
      fi

      cd simple-fullstack-app

      # Fix for divergent branches
      git config pull.rebase false
      git pull origin main

      cd backend
      npm install

      # Restart backend with PM2
      pm2 delete backend || true
      pm2 start server.js --name backend

      # Optional: Save PM2 state
      pm2 save
    EOF
