name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy App
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Update system and install dependencies
            sudo apt update
            sudo apt install -y nodejs npm nginx git
            sudo npm install -g pm2

            # Clone or pull latest code
            mkdir -p ~/app
            cd ~/app
            if [ ! -d "simple-fullstack-app" ]; then
              git clone https://github.com/Shri9345/simple-fullstack-app.git
            else
              cd simple-fullstack-app
              git pull origin main
            fi

            # Start backend
            cd ~/app/simple-fullstack-app/backend
            npm install
            pm2 stop backend || true
            pm2 start server.js --name backend

            # Copy frontend to Nginx
            sudo cp -r ~/app/simple


      - name: Deploy backend
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Stop on error
            sudo apt update
            sudo apt install -y nodejs npm nginx git
            sudo npm install -g pm2

            mkdir -p ~/app
            cd ~/app

            if [ ! -d "simple-fullstack-app" ]; then
              git clone https://github.com/Shri9345/simple-fullstack-app.git
            else
              cd simple-fullstack-app
              git fetch origin
              git reset --hard origin/main
              cd ..
            fi

            cd simple-fullstack-app/backend
            npm install

            pm2 delete backend || true
            pm2 start server.js --name backend

            # Optional: serve frontend if you're using it
            # sudo cp -r ~/app/simple-fullstack-app/frontend/* /var/www/html/
            # sudo systemctl reload nginx
          EOF
