name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy backend
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo apt update
          sudo apt install -y nodejs npm nginx
          if [ ! -d "app" ]; then mkdir app; fi
          cd app
          if [ ! -d "simple-fullstack-app" ]; then git clone https://github.com/Shri9345/simple-fullstack-app.git; fi
          cd simple-fullstack-app
          git pull origin main
          cd backend
          npm install
          pm2 stop server || true
          pm2 start server.js --name backend
        EOF
